version: "3"

volumes:
  pgdata: null
  redisdata: null
  static_spotifly: null

services:
  spotifly:
    restart: always
    build: ./projects/spotifly
    image: thatcherthornberry/spotifly:latest
    command: bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn music.wsgi:application --bind 0.0.0.0:8001"
    expose:
      - 8001
    volumes:
      - static_spotifly:/app/spotifly/staticfiles
    env_file:
      - ./projects/spotifly/.env
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
  redis:
    restart: always
    image: redis:6
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data
  scheduler:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqscheduler --queue default
    env_file:
      - .env
    depends_on:
      - "redis"
  worker:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqworker default
    env_file:
      - .env
    depends_on:
      - "redis"
