services:
  nginx:
      restart: always
      image: nginx:1.15-alpine
      volumes:
        - static_$PROJECT_NAME:/app/$PROJECT_NAME/staticfiles
        - ./nginx/$ENV:/etc/nginx/conf.d # this is how we use custom nginx build
      ports:
        - "80:80"
        - "443:443"